packages:
  - "packages/*"
  - "packages/config/*"

catalog:
  tsdown: 0.21.4
  typescript: 5.9.3
  zod: 4.3.6

catalogs:
  vitest:
    vitest: 4.1.0
    "@vitest/coverage-v8": 4.1.0

linkWorkspacePackages: true
blockExoticSubdeps: true
enableGlobalVirtualStore: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200