packages:
  - "packages/*"
  - "packages/config/*"
  - "!packages/config"

catalog:
  tsdown: 0.21.7
  typescript: 6.0.2
  zod: 4.3.6

catalogs:
  react:
    react: 19.2.5
    "react-dom": 19.2.5
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
  vitest:
    vitest: 4.1.4
    "@vitest/coverage-v8": 4.1.4

linkWorkspacePackages: true

blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@rut-toolkit/core"
  - "@rut-toolkit/zod"