blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions (Q&A)
    url: https://github.com/matcastaneda/rut-toolkit/discussions
    about: Need help using the library? Have a general question? Ask here!
  - name: 🐛 Report a Security Vulnerability
    url: https://github.com/matcastaneda/rut-toolkit/security/policy
    about: Please do not open a public issue for security flaws. Click here instead.