name: 🧪 Unit Tests

on:
  pull_request:
    branches: ["*"]
    paths-ignore:
      - '**/*.md'
      - '.vscode/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/DISCUSSION_TEMPLATE/**'
      - 'LICENSE'
      - 'FUNDING.yml'
  push:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
      - '.vscode/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/DISCUSSION_TEMPLATE/**'
      - 'LICENSE'
      - 'FUNDING.yml'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  FORCE_COLOR: 3
  SKIP_ENV_VALIDATION: true

jobs:
  test:
    name: 🧪 Run Tests & Size Check
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: write 
      pull-requests: write 
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🔧 Setup Environment
        uses: ./.github/actions/setup-environment

      - name: 📊 Run tests with coverage
        run: pnpm test:coverage

      - name: 📈 Upload Codecov
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/coverage/lcov.info" 
          slug: ${{ github.repository }}
          fail_ci_if_error: true
